/* =============================================================
   701 PARFUM — Configuración y catálogo
   Generado desde el panel el 14/9/2026, 05:23:59.
   Se puede editar a mano igual: es un archivo de texto común.
   ============================================================= */

const CONFIG = {
  marca: '701 PARFUM',
  slogan: 'Aromas que hablan por vos',
  instagram: '701_parfum',
  instagramAlt: 'fmartinn_22',

  // WhatsApp con código de país, sin +, sin espacios ni guiones.
  // Vacío ('') = los pedidos van al DM de Instagram.
  whatsapp: '5492975925565',

  moneda: 'ARS',            // pesos argentinos
  envio: null,              // null = "a coordinar"
  envioGratisDesde: 0,

  email: 'contacto@701parfum.com',
  ciudad: 'Argentina 🇦🇷',
};

/* -------------------------------------------------------------
   CATÁLOGO
   categoria: 'hombre' | 'mujer' | 'unisex'
   stock: true = "Stock inmediato" · false = "Por encargo"
   oculto: true = no aparece en la web (por ejemplo, si falta la foto)
   ------------------------------------------------------------- */
const PRODUCTOS = [
  {
    id: 'hawas-kobra',
    nombre: 'Hawas Kobra',
    marca: 'Rasasi',
    categoria: 'hombre',
    familia: 'Amaderado especiado',
    descripcion: 'La versión más oscura e intensa de la línea Hawas. Especias cálidas sobre maderas y ámbar, con una estela profunda ideal para la noche.',
    notas: ['Especias', 'Maderas', 'Ámbar', 'Cuero'],
    duracion: '9–11 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/hawas-kobra.webp',
    tono: ['#2a0c0c', '#7d2320'],
    destacado: true,
    stock: false,
  },
  {
    id: 'hawas-black',
    nombre: 'Hawas Black',
    marca: 'Rasasi',
    categoria: 'hombre',
    familia: 'Amaderado aromático',
    descripcion: 'Elegante y versátil. Cítricos frescos que abren paso a un corazón aromático y un fondo de maderas oscuras. Va de la oficina a la noche sin escalas.',
    notas: ['Cítricos', 'Lavanda', 'Cedro', 'Almizcle'],
    duracion: '8–10 h',
    precios: { '100 ml': 150000 },
    img: 'assets/img/hawas-black.webp',
    tono: ['#0c0c0e', '#3a3a42'],
    destacado: false,
    stock: true,
  },
  {
    id: 'hawas-atlantis',
    nombre: 'Hawas Atlantis',
    marca: 'Rasasi',
    categoria: 'hombre',
    familia: 'Acuático fresco',
    descripcion: 'La opción más fresca de Hawas. Notas acuáticas y cítricas con un fondo limpio de almizcle. Perfecto para el calor y el uso diario.',
    notas: ['Notas marinas', 'Pomelo', 'Menta', 'Almizcle'],
    duracion: '7–9 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/hawas-atlantis.webp',
    tono: ['#0a2f3d', '#2f9fb8'],
    destacado: false,
    stock: true,
  },
  {
    id: 'hawas-elixir',
    nombre: 'Hawas Elixir',
    marca: 'Rasasi',
    categoria: 'hombre',
    familia: 'Ambarado dulce',
    descripcion: 'Versión concentrada y más dulce de la línea. Frutas, especias y un fondo ambarado muy potente. Máxima proyección del catálogo.',
    notas: ['Frutas', 'Especias', 'Ámbar', 'Vainilla'],
    duracion: '10–12 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/hawas-elixir.webp',
    tono: ['#4a3208', '#d4a437'],
    destacado: true,
    stock: true,
  },
  {
    id: 'hawas-tropical',
    nombre: 'Hawas Tropical',
    marca: 'Rasasi',
    categoria: 'hombre',
    familia: 'Frutal fresco',
    descripcion: 'Frutas tropicales y notas verdes sobre una base limpia. Alegre, veraniego y muy fácil de llevar de día.',
    notas: ['Piña', 'Notas verdes', 'Coco', 'Almizcle'],
    duracion: '7–9 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/hawas-tropical.webp',
    tono: ['#0d3a2c', '#3f9e73'],
    destacado: false,
    stock: true,
  },
  {
    id: 'cdn-urban-elixir',
    nombre: 'Club de Nuit Urban Man Elixir',
    marca: 'Armaf',
    categoria: 'hombre',
    familia: 'Amaderado especiado',
    descripcion: 'Un clásico moderno. Especias, cuero y maderas con una proyección enorme y una permanencia que no baja en todo el día.',
    notas: ['Pimienta', 'Cuero', 'Vetiver', 'Ámbar'],
    duracion: '10–12 h',
    precios: { '105 ml': 50000 },
    img: 'assets/img/cdn-urban-elixir.webp',
    tono: ['#1a1226', '#5b4b7d'],
    destacado: true,
    stock: true,
  },
  {
    id: 'odyssey-artisto',
    nombre: 'Odyssey Artisto · The Red Edition',
    marca: 'Armaf',
    categoria: 'hombre',
    familia: 'Ambarado amaderado',
    descripcion: 'Presentación en estuche de cuero rojo. Fragancia cálida y sofisticada, con especias dulces y un fondo de maderas y vainilla.',
    notas: ['Especias dulces', 'Maderas', 'Vainilla', 'Ámbar'],
    duracion: '9–11 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/odyssey-artisto.webp',
    tono: ['#3d0a0a', '#c2352e'],
    destacado: false,
    stock: true,
  },
  {
    id: 'odyssey-aqua',
    nombre: 'Odyssey Aqua',
    marca: 'Armaf',
    categoria: 'hombre',
    familia: 'Acuático cítrico',
    descripcion: 'Frescura pura: cítricos y notas marinas sobre un fondo mineral. La opción diaria por excelencia, muy limpia.',
    notas: ['Limón', 'Notas marinas', 'Salvia', 'Almizcle'],
    duracion: '6–8 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/odyssey-aqua.webp',
    tono: ['#0e3c4a', '#5cc6d8'],
    destacado: false,
    stock: true,
  },
  {
    id: 'asad-elixir',
    nombre: 'Asad Elixir',
    marca: 'Lattafa',
    categoria: 'hombre',
    familia: 'Ambarado amaderado',
    descripcion: 'Potente y adictivo. Notas dulces y especiadas sobre un fondo de maderas y ámbar. Rinde muchísimo, con pocos sprays alcanza.',
    notas: ['Especias', 'Tabaco', 'Maderas', 'Ámbar'],
    duracion: '10–12 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/asad-elixir.webp',
    tono: ['#14140f', '#4f5148'],
    destacado: true,
    stock: true,
  },
  {
    id: 'vulcan',
    nombre: 'Vulcan',
    marca: 'French Avenue',
    categoria: 'hombre',
    familia: 'Amaderado intenso',
    descripcion: 'Frasco negro con serpiente en relieve. Fragancia oscura y magnética, con maderas ahumadas y un fondo ambarado.',
    notas: ['Maderas ahumadas', 'Especias', 'Ámbar', 'Almizcle'],
    duracion: '9–11 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/vulcan.webp',
    tono: ['#0c0c0c', '#4a4a52'],
    destacado: false,
    stock: true,
  },
  {
    id: 'atlantis-extrait',
    nombre: 'Atlantis Extrait',
    marca: 'French Avenue',
    categoria: 'hombre',
    familia: 'Acuático ambarado',
    descripcion: 'Extrait de alta concentración. Frescura acuática con un fondo cálido y dulce que la hace durar muchísimo más que un EDP común.',
    notas: ['Notas marinas', 'Bergamota', 'Ámbar', 'Vainilla'],
    duracion: '10–12 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/atlantis-extrait.webp',
    tono: ['#141a45', '#4b56b8'],
    destacado: false,
    stock: true,
  },
  {
    id: 'hawas-him',
    nombre: 'Hawas For Him',
    marca: 'Rasasi',
    categoria: 'hombre',
    familia: 'Acuático especiado',
    descripcion: 'El clásico de la casa y uno de los más vendidos del mundo árabe. Manzana y bergamota sobre notas marinas, con un fondo cálido de ámbar y canela. Fresco pero con presencia.',
    notas: ['Manzana', 'Bergamota', 'Notas marinas', 'Ámbar'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/hawas-him.webp',
    tono: ['#0f2b4a', '#3f7fb5'],
    destacado: true,
    stock: true,
  },
  {
    id: 'hawas-malibu',
    nombre: 'Hawas For Him Malibu',
    marca: 'Rasasi',
    categoria: 'hombre',
    familia: 'Acuático frutal',
    descripcion: 'Frasco azul degradé. Versión más veraniega de Hawas: cítricos y frutas sobre un fondo marino y limpio. Perfecto para el día y el calor.',
    notas: ['Cítricos', 'Frutas', 'Notas marinas', 'Almizcle'],
    duracion: '7–9 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/hawas-malibu.webp',
    tono: ['#0a2a3d', '#2f8fa8'],
    destacado: true,
    stock: true,
  },
  {
    id: 'odyssey-mandarin-sky',
    nombre: 'Odyssey Mandarin Sky',
    marca: 'Armaf',
    categoria: 'hombre',
    familia: 'Cítrico fresco',
    descripcion: 'Edición limitada con funda de cuero celeste. Mandarina y cítricos brillantes sobre un fondo amaderado suave. Muy fresco y fácil de usar todos los días.',
    notas: ['Mandarina', 'Cítricos', 'Notas verdes', 'Cedro'],
    duracion: '6–8 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/odyssey-mandarin-sky.webp',
    tono: ['#1d5f7d', '#f0a02a'],
    destacado: false,
    stock: true,
  },
  {
    id: 'bharara-king',
    nombre: 'Bharara King',
    marca: 'Bharara',
    categoria: 'hombre',
    familia: 'Ambarado dulce',
    descripcion: 'Viene en estuche con atomizador de bolsillo de regalo. Dulce, frutal y ambarado, con una proyección enorme y muchísima permanencia.',
    notas: ['Frutas', 'Vainilla', 'Ámbar', 'Maderas'],
    duracion: '10–12 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/bharara-king.webp',
    tono: ['#1a1210', '#7a5a3a'],
    destacado: true,
    stock: true,
  },
  {
    id: 'qaaed',
    nombre: 'Qaa\'ed',
    marca: 'Lattafa',
    categoria: 'hombre',
    familia: 'Amaderado especiado',
    descripcion: 'Frasco dorado texturado con estuche de cuero negro. Especias cálidas sobre maderas y ámbar; elegante, masculino y de noche.',
    notas: ['Especias', 'Maderas', 'Ámbar', 'Cuero'],
    duracion: '9–11 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/qaaed.webp',
    tono: ['#3a2a0c', '#d4a437'],
    destacado: false,
    stock: true,
  },
  {
    id: 'qaed-al-fursan',
    nombre: 'Qaed Al Fursan Unlimited',
    marca: 'Lattafa',
    categoria: 'hombre',
    familia: 'Frutal amaderado',
    descripcion: 'Piña y azafrán sobre un fondo de maderas y ámbar. Uno de los Lattafa más elogiados: se siente caro y rinde muchísimo.',
    notas: ['Piña', 'Azafrán', 'Maderas', 'Ámbar'],
    duracion: '9–11 h',
    precios: { '90 ml': 50000 },
    img: 'assets/img/qaed-al-fursan.webp',
    tono: ['#e8e2d4', '#c9a227'],
    destacado: true,
    stock: true,
  },
  {
    id: 'cdn-sillage',
    nombre: 'Club de Nuit Sillage',
    marca: 'Armaf',
    categoria: 'hombre',
    familia: 'Aromático especiado',
    descripcion: 'Frasco plateado de la línea Club de Nuit. Fresco y especiado, con un fondo amaderado limpio. Versátil para oficina y salidas.',
    notas: ['Bergamota', 'Pimienta', 'Vetiver', 'Almizcle'],
    duracion: '8–10 h',
    precios: { '105 ml': 50000 },
    img: 'assets/img/cdn-sillage.webp',
    tono: ['#2a2d33', '#9aa3ad'],
    destacado: false,
    stock: true,
  },
  {
    id: 'bharara-king-gold',
    nombre: 'Bharara King Gold Edition',
    marca: 'Bharara',
    categoria: 'hombre',
    familia: 'Ambarado dulce',
    descripcion: 'Frasco dorado a rayas, con atomizador de bolsillo de regalo. La versión Gold de King: dulce, frutal y ambarada, con una proyección enorme.',
    notas: ['Frutas', 'Vainilla', 'Ámbar', 'Maderas'],
    duracion: '10–12 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/bharara-king-gold.webp',
    tono: ['#3a2a08', '#e0b83c'],
    destacado: true,
    stock: true,
  },
  {
    id: 'nitro-red',
    nombre: 'Nitro Red Pour Homme',
    marca: 'Dumont Paris',
    categoria: 'hombre',
    familia: 'Especiado frutal',
    descripcion: 'Frasco rojo forrado en cuero. Frutas y especias sobre un fondo amaderado; llamativo, masculino y con buena permanencia.',
    notas: ['Frutas rojas', 'Especias', 'Cuero', 'Maderas'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/nitro-red.webp',
    tono: ['#5c0d12', '#c8323a'],
    destacado: false,
    stock: true,
  },
  {
    id: 'afnan-9pm-elixir',
    nombre: '9 PM Elixir',
    marca: 'Afnan',
    categoria: 'hombre',
    familia: 'Ambarado dulce',
    descripcion: 'La versión concentrada del 9 PM, uno de los más vendidos de Afnan. Vainilla, canela y ámbar: dulce, cálido y muy nocturno.',
    notas: ['Vainilla', 'Canela', 'Ámbar', 'Haba tonka'],
    duracion: '10–12 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/afnan-9pm-elixir.webp',
    tono: ['#2b1408', '#b06a24'],
    destacado: true,
    stock: true,
  },
  {
    id: 'vulcan-feu',
    nombre: 'Vulcan Feu',
    marca: 'French Avenue',
    categoria: 'hombre',
    familia: 'Acuático fresco',
    descripcion: 'La versión celeste de Vulcan, con la serpiente dorada en el cuello. Fresco y cítrico, para el día y el calor.',
    notas: ['Cítricos', 'Notas marinas', 'Menta', 'Almizcle'],
    duracion: '7–9 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/vulcan-feu.webp',
    tono: ['#0d5f7d', '#4fc0e0'],
    destacado: false,
    stock: true,
  },
  {
    id: 'hawas-eclat',
    nombre: 'Hawas For Her Éclat',
    marca: 'Rasasi',
    categoria: 'mujer',
    familia: 'Floral frutal',
    descripcion: 'Delicado y luminoso. Frutas suaves y flores blancas sobre una base cremosa de almizcle. Femenino, elegante y muy usable.',
    notas: ['Frutas', 'Flores blancas', 'Almizcle', 'Vainilla'],
    duracion: '7–9 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/hawas-eclat.webp',
    tono: ['#e6d5d8', '#b98a9a'],
    destacado: true,
    stock: true,
  },
  {
    id: 'hawas-diva',
    nombre: 'Hawas For Her Diva',
    marca: 'Rasasi',
    categoria: 'mujer',
    familia: 'Floral oriental',
    descripcion: 'Más intenso y nocturno que Éclat. Frutos rojos y flores sobre un fondo dulce de ámbar y vainilla. Estela marcada.',
    notas: ['Frutos rojos', 'Jazmín', 'Ámbar', 'Vainilla'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/hawas-diva.webp',
    tono: ['#4a0d24', '#a82c50'],
    destacado: true,
    stock: true,
  },
  {
    id: 'bonita-hot-pink',
    nombre: 'Bonita Hot Pink',
    marca: 'Le Falcone',
    categoria: 'mujer',
    familia: 'Floral dulce',
    descripcion: 'Frasco redondo con asa trenzada, muy lindo para regalar. Aroma dulce y floral, alegre y juvenil.',
    notas: ['Frutas dulces', 'Flores', 'Vainilla', 'Almizcle'],
    duracion: '6–8 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/bonita-hot-pink.webp',
    tono: ['#f0e6dc', '#e0518a'],
    destacado: false,
    stock: true,
  },
  {
    id: 'sweet-paradise',
    nombre: 'Sweet Paradise',
    marca: 'French Avenue',
    categoria: 'mujer',
    familia: 'Floral gourmand',
    descripcion: 'Presentación de lujo en blanco y dorado. Dulce y floral, con un fondo cremoso que se queda en la ropa por horas.',
    notas: ['Flores blancas', 'Praliné', 'Vainilla', 'Sándalo'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/sweet-paradise.webp',
    tono: ['#f2ece4', '#c9a227'],
    destacado: false,
    stock: true,
  },
  {
    id: 'historic-doria',
    nombre: 'Historic Doria',
    marca: 'Afnan',
    categoria: 'mujer',
    familia: 'Floral chipre',
    descripcion: 'Edición de colección en rosa y dorado. Floral sofisticado con un fondo amaderado; el frasco es una pieza de decoración.',
    notas: ['Rosa', 'Frutas', 'Pachulí', 'Maderas'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/historic-doria.webp',
    tono: ['#e8ccd2', '#c98ba0'],
    destacado: false,
    stock: true,
  },
  {
    id: 'miss-armaf-magnifiq',
    nombre: 'Miss Armaf Magnifiq',
    marca: 'Armaf',
    categoria: 'mujer',
    familia: 'Gourmand floral',
    descripcion: 'Dulce, cremoso y envolvente. Un gourmand elegante con muy buena permanencia y un frasco llamativo.',
    notas: ['Caramelo', 'Flores', 'Vainilla', 'Maderas'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/miss-armaf-magnifiq.webp',
    tono: ['#2b1a12', '#b07a4a'],
    destacado: false,
    stock: true,
  },
  {
    id: 'vulcan-baie',
    nombre: 'Vulcan Baie',
    marca: 'French Avenue',
    categoria: 'mujer',
    familia: 'Frutal dulce',
    descripcion: 'La versión femenina de Vulcan, en rosa con la serpiente dorada. Frutal y dulce, con carácter y mucha proyección.',
    notas: ['Frutos rojos', 'Grosella', 'Vainilla', 'Ámbar'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/vulcan-baie.webp',
    tono: ['#e85f9c', '#f2b6d0'],
    destacado: true,
    stock: true,
  },
  {
    id: 'odyssey-candee',
    nombre: 'Odyssey Candee · Special Edition',
    marca: 'Armaf',
    categoria: 'mujer',
    familia: 'Gourmand frutal',
    descripcion: 'Edición especial en rosa a rayas. Dulce tipo caramelo con frutas, divertido y muy femenino.',
    notas: ['Caramelo', 'Frutas', 'Flores', 'Vainilla'],
    duracion: '7–9 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/odyssey-candee.webp',
    tono: ['#f4dfe6', '#e58fae'],
    destacado: false,
    stock: true,
  },
  {
    id: 'kayali-eden',
    nombre: 'Kayali Eden Juicy Apple |01|',
    marca: 'Kayali',
    categoria: 'mujer',
    familia: 'Frutal floral',
    descripcion: 'Manzana jugosa sobre flores blancas y un fondo cálido de ámbar. Fresco, dulce y con una estela deliciosa. Producto premium.',
    notas: ['Manzana', 'Jazmín', 'Ámbar', 'Almizcle'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/kayali-eden.webp',
    tono: ['#5c0d1c', '#c23b52'],
    destacado: true,
    stock: true,
  },
  {
    id: 'whipped-pleasure',
    nombre: 'Whipped Pleasure · Give Me Gourmand',
    marca: 'Lattafa',
    categoria: 'mujer',
    familia: 'Gourmand',
    descripcion: 'Frasco con forma de postre, ideal para regalo. Crema batida, caramelo y vainilla: dulce de verdad y con buena duración.',
    notas: ['Crema', 'Caramelo', 'Vainilla', 'Almizcle'],
    duracion: '7–9 h',
    precios: { '75 ml': 50000 },
    img: 'assets/img/whipped-pleasure.webp',
    tono: ['#f0e2c8', '#c98b3e'],
    destacado: false,
    stock: true,
  },
  {
    id: 'cookie-crave',
    nombre: 'Cookie Crave · Give Me Gourmand',
    marca: 'Lattafa',
    categoria: 'mujer',
    familia: 'Gourmand',
    descripcion: 'Galleta, chocolate y crema. El gourmand más goloso del catálogo, con el mismo frasco de postre de la línea.',
    notas: ['Galleta', 'Chocolate', 'Crema', 'Vainilla'],
    duracion: '7–9 h',
    precios: { '75 ml': 50000 },
    img: 'assets/img/cookie-crave.webp',
    tono: ['#3b2416', '#a5713f'],
    destacado: false,
    stock: true,
  },
  {
    id: 'yara-moi',
    nombre: 'Yara Moi',
    marca: 'Lattafa',
    categoria: 'mujer',
    familia: 'Floral gourmand',
    descripcion: 'De la línea Yara, la más pedida de Lattafa entre las mujeres. Frutas y flores sobre un fondo cremoso de vainilla y sándalo. Dulce, suave y adictivo.',
    notas: ['Frutas', 'Orquídea', 'Vainilla', 'Sándalo'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/yara-moi.webp',
    tono: ['#f0e6d8', '#c9a227'],
    destacado: true,
    stock: true,
  },
  {
    id: 'berry-on-top',
    nombre: 'Berry On Top · Give Me Gourmand',
    marca: 'Lattafa',
    categoria: 'mujer',
    familia: 'Gourmand frutal',
    descripcion: 'Frasco con forma de postre y frutilla arriba, en su vitrina: espectacular para regalar. Frutos rojos con crema y vainilla.',
    notas: ['Frutilla', 'Frutos rojos', 'Crema', 'Vainilla'],
    duracion: '7–9 h',
    precios: { '75 ml': 50000 },
    img: 'assets/img/berry-on-top.webp',
    tono: ['#7d1220', '#e0576b'],
    destacado: true,
    stock: true,
  },
  {
    id: 'mallow-madness',
    nombre: 'Mallow Madness · Give Me Gourmand',
    marca: 'Lattafa',
    categoria: 'mujer',
    familia: 'Gourmand',
    descripcion: 'Malvaviscos y crema en un frasco de postre violeta, con su vitrina y estuche. Muy dulce, divertido y de los que más preguntan.',
    notas: ['Malvavisco', 'Crema', 'Vainilla', 'Almizcle'],
    duracion: '7–9 h',
    precios: { '75 ml': 50000 },
    img: 'assets/img/mallow-madness.webp',
    tono: ['#5a3a7d', '#c9a3e0'],
    destacado: false,
    stock: true,
  },
  {
    id: 'teriaq-intense',
    nombre: 'Teriaq Intense',
    marca: 'Lattafa',
    categoria: 'mujer',
    familia: 'Gourmand chocolate',
    descripcion: 'Frasco de postre con cobertura de chocolate, en vitrina y estuche. Chocolate, caramelo y vainilla: el más goloso de todos.',
    notas: ['Chocolate', 'Caramelo', 'Crema', 'Vainilla'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/teriaq-intense.webp',
    tono: ['#3b2416', '#a5713f'],
    destacado: false,
    stock: true,
  },
  {
    id: 'odyssey-marshmallow',
    nombre: 'Odyssey Marshmallow',
    marca: 'Armaf',
    categoria: 'mujer',
    familia: 'Gourmand suave',
    descripcion: 'Edición gourmand con funda estampada en pastel. Malvavisco y almendra sobre un fondo cremoso. Dulce pero liviano.',
    notas: ['Malvavisco', 'Almendra', 'Vainilla', 'Almizcle'],
    duracion: '7–9 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/odyssey-marshmallow.webp',
    tono: ['#a8d8d4', '#f0b8c8'],
    destacado: false,
    stock: true,
  },
  {
    id: 'nectar-of-ecstasy',
    nombre: 'Nectar of Ecstasy',
    marca: '',
    categoria: 'mujer',
    familia: 'Floral meloso',
    descripcion: 'Frasco amarillo con filigrana dorada, en estuche ilustrado. Miel y flores sobre un fondo cálido: dulce, luminoso y distinto a todo lo demás del catálogo.',
    notas: ['Miel', 'Flores blancas', 'Frutas', 'Ámbar'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/nectar-of-ecstasy.webp',
    tono: ['#a8760c', '#f0c93c'],
    destacado: true,
    stock: true,
  },
  {
    id: 'club-carnival-women',
    nombre: 'Club Carnival Intense Women',
    marca: '',
    categoria: 'mujer',
    familia: 'Floral ambarado',
    descripcion: 'Frasco de vidrio ámbar con medallón colgante y cristales en la tapa. Floral y cálido, elegante para la noche.',
    notas: ['Flores', 'Frutas', 'Ámbar', 'Vainilla'],
    duracion: '7–9 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/club-carnival-women.webp',
    tono: ['#4a2e08', '#d8a441'],
    destacado: false,
    stock: true,
  },
  {
    id: 'cdn-untold',
    nombre: 'Club de Nuit Untold',
    marca: 'Armaf',
    categoria: 'unisex',
    familia: 'Ambarado floral',
    descripcion: 'Uno de los más buscados. Azafrán y jazmín sobre un fondo dulce y amaderado. Estela reconocible a metros y duración altísima.',
    notas: ['Azafrán', 'Jazmín', 'Ámbar', 'Cedro'],
    duracion: '10–12 h',
    precios: { '105 ml': 50000 },
    img: 'assets/img/cdn-untold.webp',
    tono: ['#4a0f1e', '#b2364f'],
    destacado: true,
    stock: true,
  },
  {
    id: 'khair-fusion',
    nombre: 'Khair Fusion',
    marca: 'Paris Corner',
    categoria: 'unisex',
    familia: 'Frutal especiado',
    descripcion: 'Frasco dorado de diseño árabe. Frutas y especias cálidas sobre un fondo dulce; llamativo y con mucha personalidad.',
    notas: ['Frutas', 'Especias', 'Ámbar', 'Vainilla'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/khair-fusion.webp',
    tono: ['#5c3208', '#e29a2e'],
    destacado: false,
    stock: true,
  },
  {
    id: 'ishq-al-shuyukh-silver',
    nombre: 'Ishq Al Shuyukh Silver',
    marca: 'Lattafa',
    categoria: 'unisex',
    familia: 'Gourmand ambarado',
    descripcion: 'Frasco negro mate con la daga plateada en relieve. Almendra, caramelo y ámbar: dulce, cremoso y con una estela que se nota.',
    notas: ['Almendra', 'Caramelo', 'Ámbar', 'Vainilla'],
    duracion: '9–11 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/ishq-al-shuyukh-silver.webp',
    tono: ['#141416', '#9aa0a8'],
    destacado: true,
    stock: true,
  },
  {
    id: 'santal-33',
    nombre: 'Santal 33',
    marca: 'Le Labo',
    categoria: 'unisex',
    familia: 'Amaderado especiado',
    descripcion: 'El icónico de Le Labo. Sándalo cremoso con cardamomo, cuero e iris. Sobrio, reconocible y de los pocos que funcionan igual en cualquier persona.',
    notas: ['Sándalo', 'Cardamomo', 'Cuero', 'Iris'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/santal-33.webp',
    tono: ['#d8cfc0', '#8a7f6d'],
    destacado: true,
    stock: true,
  },
  {
    id: 'veneno',
    nombre: 'Veneno',
    marca: 'French Avenue',
    categoria: 'unisex',
    familia: 'Amaderado especiado',
    descripcion: 'Frasco negro con la serpiente dorada enroscada, en estuche de cuero. Oscuro, magnético y con muchísima estela. Es el que ves girando en la portada.',
    notas: ['Especias', 'Maderas', 'Ámbar', 'Cuero'],
    duracion: '9–11 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/veneno.webp',
    tono: ['#0d0d0f', '#c9a227'],
    destacado: true,
    stock: true,
  },
  {
    id: 'amber-oud-gold',
    nombre: 'Amber Oud Gold Edition',
    marca: 'Al Haramain',
    categoria: 'unisex',
    familia: 'Ambarado amaderado',
    descripcion: 'Uno de los árabes más reconocidos del mundo. Cítricos brillantes que abren paso a un fondo de ámbar y oud. Rinde muchísimo y gusta a todos.',
    notas: ['Cítricos', 'Ámbar', 'Oud', 'Almizcle'],
    duracion: '10–12 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/amber-oud-gold.webp',
    tono: ['#6b5312', '#e6cd82'],
    destacado: true,
    stock: true,
  },
  {
    id: 'odyssey-go-mango',
    nombre: 'Odyssey Go Mango',
    marca: 'Armaf',
    categoria: 'unisex',
    familia: 'Frutal tropical',
    descripcion: 'Frasco amarillo con funda estampada. Mango maduro y frutas tropicales sobre un fondo cremoso. Alegre, veraniego y de los que preguntan por la calle.',
    notas: ['Mango', 'Frutas tropicales', 'Coco', 'Vainilla'],
    duracion: '7–9 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/odyssey-go-mango.webp',
    tono: ['#8a6a0e', '#f0c23a'],
    destacado: false,
    stock: true,
  },
  {
    id: 'art-of-universe',
    nombre: 'Art of Universe',
    marca: 'Lattafa Pride',
    categoria: 'unisex',
    familia: 'Cítrico amaderado',
    descripcion: 'Edición de colección con placa metálica y librito ilustrado. Bergamota y mandarina sobre un fondo de cedro, ámbar y almizcle. El estuche es una pieza en sí.',
    notas: ['Bergamota', 'Mandarina', 'Cedro', 'Ámbar'],
    duracion: '8–10 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/art-of-universe.webp',
    tono: ['#132a52', '#4a6fa8'],
    destacado: true,
    stock: true,
  },
  {
    id: 'island-cream-macaroon',
    nombre: 'Island Cream Macaroon',
    marca: '1Scents Delights',
    categoria: 'mujer',
    familia: 'Gourmand cremoso',
    descripcion: 'Frasco con forma de malteada, en turquesa y con pedrería. Crema, coco y frutas tropicales: dulce, fresco y espectacular para regalar.',
    notas: ['Crema', 'Coco', 'Frutas', 'Vainilla'],
    duracion: '7–9 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/island-cream-macaroon.webp',
    tono: ['#0d6b70', '#4fd0d4'],
    destacado: true,
    stock: true,
  },
  {
    id: 'asad-bourbon',
    nombre: 'Asad Bourbon',
    marca: 'Lattafa',
    categoria: 'hombre',
    familia: 'Ambarado especiado',
    descripcion: 'La versión marrón de la línea Asad. Notas cálidas de bourbon y especias sobre maderas y ámbar. Más licoroso y otoñal que el Elixir.',
    notas: ['Bourbon', 'Especias', 'Maderas', 'Ámbar'],
    duracion: '9–11 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/asad-bourbon.webp',
    tono: ['#3d2317', '#9a6440'],
    destacado: false,
    stock: true,
  },
  {
    id: 'bon-bon',
    nombre: 'Bon Bon',
    marca: 'Armaf Delights',
    categoria: 'mujer',
    familia: 'Gourmand',
    descripcion: 'Viene en su caja de regalo, con el frasco en forma de postre turquesa y el macaron de chocolate arriba. Dulce, cremoso y muy llamativo.',
    notas: ['Chocolate', 'Crema', 'Caramelo', 'Vainilla'],
    duracion: '7–9 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/bon-bon.webp',
    tono: ['#0e7a80', '#5fd8de'],
    destacado: false,
    stock: true,
  },
  {
    id: 'liquid-brun',
    nombre: 'Liquid Brun',
    marca: 'French Avenue',
    categoria: 'hombre',
    familia: 'Amaderado ambarado',
    descripcion: 'Frasco marrón con la piedra dorada al frente. Maderas cálidas, ámbar y un fondo dulce; elegante, sobrio y de noche.',
    notas: ['Maderas', 'Ámbar', 'Especias', 'Vainilla'],
    duracion: '9–11 h',
    precios: { '100 ml': 50000 },
    img: 'assets/img/liquid-brun.webp',
    tono: ['#3a2018', '#8a5a3c'],
    destacado: false,
    stock: true,
  },
];
